<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###The price of one apple and one orange.

In [14]:
import numpy as np #Matrix Operator.
from scipy.linalg import solve #Open Library
A = np.array([[20,10],[17,22]]) #Creation of 2x2 matrix named as matrix A.
B = np.array([[350],[500]]) #Creation of 2x2 matrix named as matrix B.
print(A) #Display matrix A.
print(B) #Displays matrix B.
X = solve(A,B) #Solves for A and B
print(X) #Displays the final output. 
#X = np.linalg.solve(A,B) #Direct way for solving functions.
#print(X) #Displays the final output. 

[[20 10]
 [17 22]]
[[350]
 [500]]
[[10.]
 [15.]]


In [3]:
inv_A=np.linalg.inv(A) #To get the inverse of matrix A.
print(inv_A) #Displays the inverse of matrix A.
X = np.linalg.inv(A).dot(B) #Inverses matrix A then, getsthe dot product of inv_A and matrix B.
print(X) #Displays the final output. 

[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]
[[10.]
 [15.]]


In [4]:
X = np.dot(inv_A,B) #Another way of inversing and getting the dot product of matrices. 
print(X) #Displays the final output.

[[10.]
 [15.]]


###Solving for three linear equation with unknown variables of x, y, and z. 

In [ ]:
#4x+3y+2z=25
#-2x+2y+3z=-10
#3x-5y+2z=-4

In [19]:
A = np.array([[4,3,2],[-2,2,3],[3,-5,2]]) #Creation of 3x3 matrix named as matrix A.
print(A) #Display matrix A
B = np.array([[25],[-10],[-4]]) #Creation of 3x3 matrix named as matrix B.
print(B) #Display matrix B
X = solve(A,B) #From the scipy library, that solve the function.
print(X) #Displays the final output. 

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 25]
 [-10]
 [ -4]]
[[ 5.]
 [ 3.]
 [-2.]]
