<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Create a NumPy program that solves for the unknown variables of linear systems:

In [1]:
import numpy as np #Matrix operator 
A = np.array([[4,10,8],[10,26,26],[8,26,61]]) #Creation of matrix A
print(A)
print ('\n')
Inv_A = np.linalg.inv(A) #To inverse the inputs of matrix A
print(Inv_A) #Prints Inv_A
print ('\n')
B = np.array([[44],[128],[214]]) #Creation of matrix B
print(B)
print ('\n')
X = np.dot(Inv_A,B) #To get the dot product of the inverse of A and Matrix B 
print(X)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]


[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]


[[ 44]
 [128]
 [214]]


[[-8.]
 [ 6.]
 [ 2.]]
