<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Write a Python code to show as its solution. Save it as "Determinant of Matrix" in your GitHub repository.

In [7]:
import numpy as np #Matrix Operator
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]]) #To create a 3x3 matrix named as A
print(A)
print('\nDeterminant of A:')
print(round(np.linalg.det(A))) #Display the rounded off Determinang of A

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]

Determinant of A:
-14
