<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #Import Library
from numpy.linalg import eig

A = np.array([[-12,3],[4,1]]) #Creation of a 2x2 matrix named A
print(A) #Displays matrix A

inv_A = np.linalg.inv(A) #Inverse the values of matrix A
print(inv_A) #Displays the inverse of matrix A

B = np.array([[0],[0]]) #Creation of a 2x2 matrix named B
print(B) #Displays matrix B

X = np.dot(inv_A,B) #Dot product of the inverse of matrix A and matrix B
print(X) #Displays the dot product
#X = solve(A,B)
#print(X)

[[-12   3]
 [  4   1]]
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]
[[0]
 [0]]
[[0.]
 [0.]]


##Example 1


In [2]:
A = np.array([[-6,3],[4,5]]) #Creation of a 2x2 matrix named A
print(A) #Displays matrix A

w,v = np.linalg.eig(A)
#Display the output
print("The eigenvalue/s is/are:",w)
print("The right eigenvectors are:",v)
#x = v.round()
#print(x)

[[-6  3]
 [ 4  5]]
The eigenvalue/s is/are: [-7.  6.]
The right eigenvectors are: [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


##Example 2


In [3]:
A = np.array([[2,2,4],[1,3,5],[2,3,4]]) #Creation of a 3x3 matrix named A
print(A) #Displays matrix A
s,t = np.linalg.eig(A)
print(s.round())
print(t.round())
#Compute eigenvalues and right eigenvectors of a square array
c = np.dot(A,t.round()) #dot product of A and t
print(c) #Displays the final output

[[2 2 4]
 [1 3 5]
 [2 3 4]]
[ 9.  1. -1.]
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
