<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Problem 1

In [19]:
Eq1 = np.array([[1,1,1],[1,0,4],[0,0,5]]) #Creates a 3x3 matrix named Eq1
Eq2 = np.array([[89],[89],[95]]) #Creates a 1x3 matrix named Eq2
amt = np.linalg.inv(Eq1).dot(Eq2) #Solves for how much each student have
print(amt) #Displays the final answer

[[13.]
 [57.]
 [19.]]


###Problem 2

In [21]:
import numpy as np #Matrix Operator
C = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]]) #Creates a 3x3 matrix named C
print(C,"\n") #Displays matrix C
Inv_C = np.linalg.pinv(C) #Inverses the values of matrix C
print(Inv_C,"\n") #Displays the inverse values of matrix C
B = np.array([[5],[15],[-20]]) #Creates a 1x3 matrix named B
print(B,"\n") #Displays matrix B
X = np.dot(Inv_C, B) #Gets the dot product of Inv_C and matrix B
print(X) #Displays final output

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]] 

[[ 0.01048951  0.03146853 -0.04195804]
 [-0.0034965  -0.01048951  0.01398601]
 [ 0.0034965   0.01048951 -0.01398601]] 

[[  5]
 [ 15]
 [-20]] 

[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


###Problem 3




In [16]:
import numpy as np #Matrix Operator
from numpy.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]]) #Creates a 3x3 matrix named A
print(A,"\n") #Displays matrix A
w,v = np.linalg.eig(A) 
#Used to find the eigenvalues and eigenvectors of matrix A.
print("The eigenvalue/s is/are:\n",w.round(),"\n") #Displays the rounded eigenvalues
print("The eigenvector/s is/are:\n",v.round()) #Displays the rounded eigenvectors

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalue/s is/are:
 [-1.  3.  2.] 

The eigenvector/s is/are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
