<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###To find the inverse of matrix , the matrix is passed to the linalg.inv() of the NumPy module: 

In [ ]:
import numpy as np #Matrix operator 
A = np.array([[4,3],[-5,9]]) #Creation of matrix A
print(A)
Inv_A = np.linalg.inv(A) #To inverse the inputs of matrix A
print(Inv_A) #Prints Inv_A

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [ ]:
B = np.array([[20],[26]]) #Creation of matrix B
print(B)

[[20]
 [26]]


In [ ]:
X = np.linalg.inv(A).dot(B) #To get the dot product of the inverse of A and Matrix B (1st Way)
print(X)

[[2.]
 [4.]]


In [ ]:
X = np.dot(Inv_A,B) #To get the dot product of the inverse of A and Matrix B (2nd Way)
print(X)

[[2.]
 [4.]]


In [ ]:
A = np.array([[20,10],[17,22]]) #Creation of matrix A
print(A)
Inv_A = np.linalg.inv(A) #To inverse the inputs of matrix A
print(Inv_A) 

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [ ]:
B = np.array([[350],[500]]) #Creation of matrix B
print(B)


[[350]
 [500]]


In [ ]:
X = np.dot(Inv_A,B) #To get the dot product of the inverse of A and Matrix B 
print(X)

[[10.]
 [15.]]


###To check if the answer is correct

In [ ]:
B = np.dot(A,X) #To check if the answer is correct
print(B)

[[350.]
 [500.]]


###Let's now solve a system of three linear equations

In [ ]:
import numpy as np #Matrix operator 
A = np.array([[4,3,2],[-2,2,3],[3,-5,2]]) #Creation of matrix A
print(A)
print ('\n')
Inv_A = np.linalg.inv(A) #To inverse the inputs of matrix A
print(Inv_A) #Prints Inv_A
print ('\n')
B = np.array([[25],[-10],[-4]]) #Creation of matrix B
print(B)
print ('\n')
X = np.dot(Inv_A,B) #To get the dot product of the inverse of A and Matrix B 
print(X)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]


[[ 0.15447154 -0.1300813   0.04065041]
 [ 0.10569106  0.01626016 -0.1300813 ]
 [ 0.03252033  0.23577236  0.11382114]]


[[ 25]
 [-10]
 [ -4]]


[[ 5.]
 [ 3.]
 [-2.]]
