<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python Program to Inverse


In [8]:
import numpy as np #Matrix operator
A=np.array([[1, 2],[4, 7]]) #To create a 2x2 matrix named as Matrix A. 
invA=(np.linalg.inv(A)) #To inverse Matrix A
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [9]:
C=np.dot(A,invA) #To get the product of A and invA
print(C)

[[1. 0.]
 [0. 1.]]


In [19]:
##Python Program to Transpose a 3x3 Matrix A=([6, 1, 1],[4, -2, 5],[2, 8, 7])
A=np.array([[6, 1, 1],[4, -2, 5],[2, 8, 7]]) #To create a 3x3 matrix named as Matrix A. 
print(A)
B=np.transpose(A) #To transpose Matrix A
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [27]:
##Python Program to Inverse a 3x3 Matrix A=([6, 1, 1],[4, -2, 5],[2, 8, 7])
A=np.array([[6, 1, 1],[4, -2, 5],[2, 8, 7]]) #To create a 3x3 matrix named as Matrix A. 
invA=(np.linalg.inv(A)) #To inverse Matrix A
print(invA)

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [28]:
productAB=np.dot(A,invA) #To get the product of A and B
print(productAB)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


In [23]:
##Python Program to Inverse a 4x4 Matrix A=([6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7])
A=np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]]) #To create a 4x4 matrix named as Matrix A. 
invA=(np.linalg.inv(A)) #To inverse Matrix A
print(invA)
print()
B=np.transpose(invA) #To transpose inversed Matrix A
print(B)

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]

[[ 0.13368984 -0.00229183 -0.12987013  0.11000764]
 [ 0.10695187  0.02673797  0.18181818 -0.28342246]
 [ 0.02139037  0.14820474  0.06493506 -0.11382735]
 [-0.09090909 -0.12987013 -0.02597403  0.23376623]]
