<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Question 1. Create a Python code that displays a square matrix whose length is 5. 

In [19]:
import numpy as np #Matrix operator
square_matrix = np.identity(5) #Creation of a 5x5 matrix since a square matrix must have equal lenght(columns) and width(rows). 
print(f'Square Matrix whose length is 5: \n{square_matrix}') #Displays the final output

Square Matrix whose length is 5: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


###Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero.


In [25]:
square_matrix = np.array([[1,2,3,4],[0,2,4,6],[0,0,3,6],[0,0,0,4]]) #Creation of a 4x4 matrix named as square matrix
print('A square matrix whose elements below the principal diagonal are zero: ') #Text message indicating the result
print(square_matrix) #Displays the final output

A square matrix whose elements below the principal diagonal are zero: 
[[1 2 3 4]
 [0 2 4 6]
 [0 0 3 6]
 [0 0 0 4]]


###Question 3. Create a Python code that displays a square matrix which is symmetrical.

In [26]:
square_matrix = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]]) #Creation of a 5x5 matrix named as square matrix
print('A square matrix which is symmetrical: ') #Text message indicating the result
print(square_matrix) #Displays the final output

A square matrix which is symmetrical: 
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


###Question 4. What is the inverse of matrix C? Show your solution by python coding.

In [2]:
C = np.array([[1,2,3],[2,3,4],[3,3,-2]]) #Creation of a 3x3 matrix named C
print(C) #Prints matrix C
print() #Gives spaces in between the two matrices.
Inv_C = np.linalg.inv(C) #Inverses the inputs of matrix C
print(Inv_C) #Prints the Inv_C

[[ 1  2  3]
 [ 2  3  4]
 [ 3  3 -2]]

[[-3.6  2.6 -0.2]
 [ 3.2 -2.2  0.4]
 [-0.6  0.6 -0.2]]


###Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. 

In [8]:
C = np.array ([[1,2,3], [2,3,3],[3,4,-2]]) #Creation of a 3x3 matrix named C
detOfC = np.linalg.det(C) #Gives the determinant of matrix C
print("The determinant of the given matrix in Question 4 is:") #Text message indicating the result
print(int(detOfC)) #Displays the final output

The determinant of the given matrix in Question 4 is:
5


###Question 6. Find the roots of the linear equations by showing its python codes 

In [6]:
A = np.array([[5,4,1],[10,9,4], [10,13,15]]) #Creation of a 3x3 matrix named A, taht contains the equation. 
B = np.array([[[3.4],[8.8],[19.2]]]) #Creation of a 2x3 matrix named B, that contains the constants.
roots = np.linalg.inv(A) @ B #To find the roots of the linear equation
print("The roots of the given linear equations are:") #Text message indicating the result
print(roots) #Displays the final output

The roots of the given linear equations are:
[[[0.2]
  [0.4]
  [0.8]]]
