<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Practical_Lab_Exam_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Problem 1

In [11]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]]) 
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]]) 

a = np.dot(A,B)
b = np.add(D,D)
c = 2*C

print("A. AB")
print(a)
print("\nB. D+D")
print(b)
print("\nC. 2*C")
print(c)

A. AB
[[22 28]
 [49 64]]

B. D+D
[[2 4]
 [6 8]]

C. 2*C
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


###Problem 2

In [10]:
import numpy as np
X = np.array([5,3,-1])

print(X)
print('\ntype of array', type(X))
print('size of array : ', X.size)
print('shape of array: ', X.shape)
print('dimension of array:', X.ndim)

[ 5  3 -1]

type of array <class 'numpy.ndarray'>
size of array :  3
shape of array:  (3,)
dimension of array: 1
