<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Question 1

In [14]:
import numpy as np
A = np.array([1, 1, 1, 1,])
C = np.diag(A)
print(C)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


##Question 2

In [17]:
import numpy as np 
A = np.array([1, 1, 1, 1])
C = np.diag(A)

#To double the value of array C
print(C*2)

[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]


##Question 3

In [10]:
import numpy as np
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

#To compute the cross of arrays A and B
cross = np.cross(A,B)
print(cross)

[20 -4 -3]
