<a href="https://colab.research.google.com/github/Nickamaes/Linear-Algebra_58109/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####Matrix and its Operation


In [1]:
import numpy as np
A = np.array([[-5,0],[4,1]]) #This is matrix A
print(A)
B = np.array([[6,-3],[2,3]]) #This is matrix B
print(B)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]


In [ ]:
import numpy as np
A = np.array([[-5,0],[4,1]]) 
B = np.array([[6,-3],[2,3]]) 
print(A+B)

[[ 1 -3]
 [ 6  4]]


In [ ]:
import numpy as np
A = np.array([[-5,0],[4,1]]) 
B = np.array([[6,-3],[2,3]]) 
print(B-A)

[[11 -3]
 [-2  2]]


In [ ]:
import numpy as np
A = np.array([[-5,0],[4,1]]) 
B = np.array([[6,-3],[2,3]]) 
print(A-B)

[[-11   3]
 [  2  -2]]
